version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: daily    
  - package-ecosystem: "maven"
    directory: "/api"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "hantsy"
    assignees:
      - "hantsy"
    labels:
      - "dependencies"
      - "maven"
